---
title: "data_cleaning"
author: "Gordon Blasco"
date: "February 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(scales)
library(sf)
library(leaflet)
library(tmap)

# Read in data
gulls <- read_csv("seagulls_small.csv")
```


```{r}
# Make an even smaller test dataset

gulls_tiny <- gulls %>% 
  filter(
    county == 'Santa Barbara' |
      county == 'Orange' |
      county == 'Los Angeles'
  ) 

write_csv(gulls_tiny, "seagulls_tiny.csv")
```


```{r}
gulls_final <- gulls %>% 
  filter(
    county == 'Santa Barbara' &
      common_name != 'Western Gull'
  )  %>% 
  group_by(common_name) %>% 
  summarize(
    n = sum(observation_count)
  ) %>% 
  mutate(
    total = sum(n),
    prop = n / total
  ) %>% 
  arrange(-prop) %>% 
  mutate(common_name = factor(common_name, levels = common_name))

prop_plot <- ggplot(gulls_final, aes(x = common_name, y = prop)) +
  geom_col() +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_continuous(labels=percent_format(),
                     expand = c(0,0)) +
  theme_bw() +
  coord_flip()

prop_plot
```


####MAP####

```{r}
#Class lab attempt
tmap_mode("view")

gulls_sf <- st_as_sf(gulls, coords = c("longitude", "latitude"), crs = 4326)


ca <- read_sf(dsn = ".", layer = "california_county_shape_file") # Read data

st_crs(ca) = 4326 # Set CRS

ca_map <- tm_shape(ca) +
  tm_polygons() +
  tm_fill(g)
  
ca_map

```

```{r}

gulls_tidy <- gulls %>% 
  mutate(year = year(observation_date)) %>% 
  filter(observation_count != 'X') %>% 
  rename(lat = latitude, 
         long = longitude) 

gulls_tidy$year <- as.integer(gulls_tidy$year)
gulls_tidy$observation_count <- as.numeric(gulls_tidy$observation_count)
gulls_tidy$month <- month(gulls_tidy$observation_date, label = FALSE, abbr = TRUE)
gulls_tidy$month <- month.abb[gulls_tidy$month]


gulls_mean_final <- gulls_tidy %>% 
  group_by(common_name, month, county) %>% 
  summarise(
    mean = round(mean(observation_count),1)
  ) 

gull_mean <- read_csv("seagulls_mean_raw.csv")

gull_choice <- gull_mean %>% 
  filter(common_name == "Western Gull") %>% 
  spread(key = "month", value = "mean") %>% 
  rename('NAME' = 'county')
#gull_choice[ , 3:14][is.na(gull_choice[ , 3:14] ) ] = 0 


ca_gull <- full_join(ca, gull_choice)

ca_gull[ , 10][is.na(ca_gull[ , 10] ) ] = "Western Gull"
ca_gull[ , 11:22][is.na(ca_gull[ , 11:22] ) ] = 0 
str(ca_gull)
```


```{r}
max_val <- max(ca_gull$Jan)
bins <- c(seq(0, max_val, length.out = 7))
pal <- colorBin("YlOrRd", domain = ca_gull$Jan, bins = bins)

labels <- sprintf(
  "<strong>%s</strong><br/>%g Seagulls per Sighting",
  ca_gull$NAME, ca_gull$Jan
) %>% lapply(htmltools::HTML)


leaflet(ca_gull) %>% 
  setView(-120.74, 37.61, 5) %>%
  addPolygons(
    fillColor = ~pal(Jan),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
    weight = 2,
    color = "#666",
    dashArray = "",
    fillOpacity = 0.7,
    bringToFront = TRUE),
  label = labels,
  labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 5px"),
    textsize = "13px",
    direction = "auto"))

```



```{r}
#demo(nc, ask = FALSE, echo = FALSE)
#plot(st_geometry(nc))



m <- leaflet() %>%
  addTiles() %>%  
  setView(-119.4179, 36.7783, zoom = 5) %>%
  addMarkers(lng=-72.690940, lat=41.651426, popup="<b>Hello</b><br><a href='http://www.trendct.org'>-TrendCT.org</a>")
m 
```

```{r}
m <- leaflet(gulls) %>% 
  addTiles('http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png', attribution='Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>') %>%
    setView(-119.4179, 36.7783, zoom = 5) %>% 
    addCircles(~longitude, ~latitude, popup=gulls$common_name, weight = 3, radius=40, 
                   color="#ffa500", stroke = TRUE, fillOpacity = 0.8) %>% 
    addLegend("bottomright", colors= "#ffa500", labels="GULLS!", title="In CALI")
m
```



